### ISSUE TITLE
How do you install this? 

### ISSUE THREAD

**Issue by alexdresko** [jhanssen/node-homeseer-myq#1]

**Comment by jhanssen** [comment]
This was abandoned before I could get a chance to polish it due to me not using homeseer anymore but it should still work. It's not very user friendly though. The reason this exists as a node program is that I'm not very fond of writing code in .net so I wrote a small homeseer plugin that exposes some of their API over a websocket (note, there's no authentication here), see https://github.com/jhanssen/HSPI_WebSocket (binaries available at http://jhanssen.github.io/). Once that has been installed you'll need to create a file called `myq-cfg/myq.json` in the directory where this program exists and put in (with your actual myq username and password obviously)

``` javascript
{"username":"","password":""}
```

and then modify the websocket URL in src/myq.js to point to your homeseer device (the port should still be 8087 unless you change that in the plugin config). Now you should be able to start it up and garage door devices should appear in homeseer.
